const KEY='cbl_v42_state', OLD_KEYS=['cbl_v41_state','cbl_v40_state','wme_v31_state','wme_v3_state'];
const waste=[
['W01','処理会社の事業構造','廃棄物が発生してから最終処分までの全体像を経営者として説明できる'],['W02','一廃・産廃・特別管理産廃','区分・処理責任・許可の違いを整理する'],['W03','許可証を読む','業・施設許可、品目、区域、条件を確認できる'],['W04','排出事業者責任と処理業者責任','委託側・受託側の責任を区別する'],['W05','委託契約書を読む','契約の重要確認事項を理解する'],['W06','マニフェストの全体像','排出から最終処分終了までの情報の流れを説明する'],['W07','JWNET実務','電子マニフェストの社内運用を理解する'],['W08','契約・マニフェストの事故','誤登録等の是正と再発防止を考える'],['W09','収集運搬と原価','車両・人員・ルート等から回収原価を考える'],['W10','感染性廃棄物の実務','分類・容器・保管・運搬・処理を理解する'],['W11','焼却処理の仕組み','投入から燃焼・熱回収・排ガス・灰まで理解する'],['W12','焼却以外の処理と最終処分','破砕等の処理と残さの行先を理解する'],['W13','焼却炉を構成する設備','主要設備の役割と停止影響を理解する'],['W14','ボイラー・蒸気・熱回収','熱回収・資格・停止リスクを整理する'],['W15','電気・受変電設備','電気設備・保安管理・停電影響を学ぶ'],['W16','排ガス・排水・公害防止','環境基準・測定・異常時対応を整理する'],['W17','工場の重要資格・選任者','法定選任と属人化リスクを見える化する'],['W18','定修・予防保全・停止リスク','定修・予備品・復旧・バックアップを整理する'],['W19','市町村の一般廃棄物処理','市町村責任・計画・民間活用を理解する'],['W20','自治体施設の定修・故障時受入れ','自治体案件の契約・手続・能力を確認する'],['W21','災害廃棄物・広域処理','災害時の民間事業者の役割を理解する'],['W22','処理原価を理解する','人件費・燃料・薬剤・電力・修繕等を分解する'],['W23','料金・契約・顧客別採算','条件を含めた顧客採算を考える'],['W24','経営者として工場を管理する','法令・設備・人材・顧客・行政・BCPを統合する']];
const agri=[
['A01','日本農業の全体像','市場規模・経営体・主要作物・構造変化を説明できる'],['A02','農業のサプライチェーン','生産から流通・加工・販売までの商流を理解する'],['A03','農業経営体・農業法人','法人化・大型化・農地集約の動きを理解する'],['A04','千葉県・成田周辺の農業','地域の主要品目・プレイヤー・特徴を把握する'],['A05','米のビジネス','生産・価格・流通・収益構造を理解する'],['A06','露地野菜のビジネス','作型・収量・労働・販売の特徴を理解する'],['A07','施設園芸のビジネス','ハウス・環境制御・暖房費・収益構造を理解する'],['A08','果樹・高付加価値農業','長期投資とブランド・直販を理解する'],['A09','農業のPLと原価','反収・単価・歩留まり・労務費等で採算を見る'],['A10','農産物流通と販売','JA・市場・契約栽培・直販・ECを比較する'],['A11','農地・農地法・参入制度','農地利用と企業参入の基本制度を理解する'],['A12','農業政策・補助制度','政策方向と支援制度を事業判断に使う'],['A13','人材・雇用・農作業受託','人手不足と外部サービスの構造を理解する'],['A14','スマート農業','自動化・AI・ドローン・環境制御の投資効果を考える'],['A15','農業法人のケース分析','実在企業を市場・収益・競争優位で分析する'],['A16','自社が農業参入するなら','参入目的・方式・販売先・投資・リスクを整理する']];
const circular=[
['C01','余熱利用の基本','焼却施設から利用可能な熱の形・量・時間帯を整理する'],['C02','施設園芸の熱需要','作物・季節・ハウス規模別の熱需要を理解する'],['C03','作物候補の選定','市場性・栽培条件・熱需要から候補作物を比較する'],['C04','立地・導管・インフラ','工場と農業施設の距離・熱輸送・電力・水等を整理する'],['C05','事業スキーム','自社営農・農業法人連携・熱販売等の方式を比較する'],['C06','法制度・許認可・補助制度','農地・建築・環境・補助制度等の確認事項を整理する'],['C07','投資採算・FS','CAPEX・OPEX・売上・熱価値・回収期間を検証する'],['C08','実証から意思決定','小規模実証・KPI・撤退基準・本投資条件を決める']];
const courses={waste:{name:'廃棄物',items:waste},agri:{name:'農業',items:agri},circular:{name:'余熱 × 農業',items:circular}};
function fresh(){return{completed:[],notes:{},company:{},current:'W01',lastUpdated:''}}
function load(){let raw=localStorage.getItem(KEY);if(raw){try{return{...fresh(),...JSON.parse(raw)}}catch(e){}} for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(!raw)continue;try{const o=JSON.parse(raw),s=fresh();(o.completed||[]).forEach(n=>s.completed.push(/^\d+$/.test(n)?'W'+n:n));for(const [n,v] of Object.entries(o.lessonNotes||{}))s.notes[/^\d+$/.test(n)?'W'+n:n]={learned:v.understanding||v.fact||'',fact:v.ourCompany||'',next:v.mission||v.question||'',source:v.source||''};return s}catch(e){}}return fresh()}
let state=load(),page='home';
function save(){state.lastUpdated=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));const e=document.getElementById('saveState');if(e){e.textContent='保存しました';setTimeout(()=>e.textContent='自動保存',800)}}
const nav=[['home','HOME'],['waste','廃棄物｜24回'],['agri','農業｜16回'],['circular','余熱 × 農業｜8回'],['company','会社の現在地'],['records','学習記録']];
function renderNav(){navEl=document.getElementById('nav');navEl.innerHTML=nav.map(x=>`<button class="nav-btn ${page===x[0]?'active':''}" data-p="${x[0]}">${x[1]}</button>`).join('');navEl.querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.p))}
function go(p,arg){page=p;renderNav();document.getElementById('sidebar').classList.remove('open');render(p,arg)}
function item(id){for(const c of Object.values(courses)){const x=c.items.find(v=>v[0]===id);if(x)return{course:c.name,row:x}}}
function courseOf(id){return id[0]==='W'?'waste':id[0]==='A'?'agri':'circular'}
function pct(k){const c=courses[k];return Math.round(c.items.filter(x=>state.completed.includes(x[0])).length/c.items.length*100)}
function next(k){return courses[k].items.find(x=>!state.completed.includes(x[0]))||courses[k].items.at(-1)}
function promptFor(id){const it=item(id),title=it.row[1],goal=it.row[2],domain=it.course;return `私は経営者として「${domain}」を体系的に学んでいます。\n毎日30分程度、ChatGPTとの対話で学習します。\n\n【今日のテーマ】\n${id}｜${title}\n\n【今日のゴール】\n${goal}\n\n【学習方針】\n・初心者にも分かる言葉で説明してください。\n・単なる知識ではなく、経営者が判断に使える理解を目指します。\n・最新情報が重要な内容はWeb検索し、官公庁・自治体・公的統計・一次情報を優先してください。\n・事実、一般論、推測を区別してください。\n・一方的に長く説明せず、私への質問を挟みながら一問ずつ対話形式で進めてください。\n\n【30分の進め方】\nSTEP1｜基礎を理解する（約8分）\n今日のテーマの全体像、重要用語、仕組みを説明してください。\n\nSTEP2｜市場・制度・実務を調べる（約7分）\n今日のテーマに必要な最新データ、制度、業界動向、実務上のポイントを確認してください。\n\nSTEP3｜経営者として考える（約7分）\n収益、コスト、投資、人材、リスク、競争力、法令・制度の観点から重要な問いを出してください。\n\nSTEP4｜自社・事業に当てはめる（約5分）\n私に一問ずつ質問し、自社への当てはめを手伝ってください。${domain==='余熱 × 農業'?' 廃棄物焼却施設の余熱を農業に利用する事業性を意識してください。':''}\n\nSTEP5｜サイト反映用データを作る（約3分）\n最後に、下記の形式をそのまま使って出力してください。各項目は簡潔に。確認できた事実と推測・課題候補を混ぜないでください。\n\n[SITE_DATA]\nTHEME: ${id}｜${title}\nLEARNED: 今日わかった一般知識・業界知識\nOUR_FACT: 自社について確認できた事実。なければ「なし」\nISSUE: 自社の課題候補。断定できなければ「要確認」と明記。なければ「なし」\nUNKNOWN: まだ分からないこと・次に確認すること。なければ「なし」\nSOURCE: 根拠URL・資料名・確認日。なければ「なし」\n[/SITE_DATA]\n\nこのブロックはサイトへそのままコピペするため、見出し名を変更しないでください。\nではSTEP1から始めてください。`}
function render(p,arg){document.getElementById('pageTitle').textContent=Object.fromEntries(nav)[p]||'学習';const c=document.getElementById('content');if(p==='home')home(c);else if(['waste','agri','circular'].includes(p))course(c,p);else if(p==='lesson')lesson(c,arg||state.current);else if(p==='company')company(c);else records(c)}
function home(c){const total=Object.values(courses).reduce((a,x)=>a+x.items.length,0),done=state.completed.length; c.innerHTML=`<div class="hero"><span class="badge blue">DAILY 30 MINUTES</span><h2>今日も30分、ChatGPTで学ぶ。</h2><p class="muted">このサイトの役割は3つだけ。テーマを選ぶ → ChatGPTで学ぶ → 分かったことを残す。</p><div class="today-flow"><span class="flow-step">1 テーマを選ぶ</span><span class="flow-arrow">→</span><span class="flow-step">2 プロンプトをコピー</span><span class="flow-arrow">→</span><span class="flow-step">3 ChatGPTで30分</span><span class="flow-arrow">→</span><span class="flow-step">4 記録・完了</span></div></div>
<div class="grid cols-3"><div class="card course-card"><div class="small muted">廃棄物</div><div class="metric">${pct('waste')}%</div><div class="progress"><i style="width:${pct('waste')}%"></i></div><h3 style="margin-top:14px">次回 ${next('waste')[0]}｜${next('waste')[1]}</h3><button class="btn big-action" onclick="go('lesson','${next('waste')[0]}')">廃棄物を学ぶ</button></div>
<div class="card course-card agri"><div class="small muted">農業</div><div class="metric">${pct('agri')}%</div><div class="progress"><i style="width:${pct('agri')}%"></i></div><h3 style="margin-top:14px">次回 ${next('agri')[0]}｜${next('agri')[1]}</h3><button class="btn big-action" onclick="go('lesson','${next('agri')[0]}')">農業を学ぶ</button></div>
<div class="card course-card circular"><div class="small muted">余熱 × 農業</div><div class="metric">${pct('circular')}%</div><div class="progress"><i style="width:${pct('circular')}%"></i></div><h3 style="margin-top:14px">次回 ${next('circular')[0]}｜${next('circular')[1]}</h3><button class="btn big-action" onclick="go('lesson','${next('circular')[0]}')">新規事業を研究する</button></div></div>
<div class="grid cols-2" style="margin-top:16px"><div class="card"><h3>全体進捗</h3><div class="metric">${done}/${total}</div><p class="muted">学習回数だけでなく、学習から見えた「会社の事実・課題候補・未確認事項」も自動で蓄積します。</p></div><div class="card"><h3>直近の学習</h3>${recent(4)}</div></div>`}
function course(c,k){const co=courses[k],done=co.items.filter(x=>state.completed.includes(x[0])).length;c.innerHTML=`<div class="section-head"><div><h2>${co.name}</h2><div class="muted">${done}/${co.items.length} 完了｜テーマを開いてプロンプトをコピーします。</div></div><strong>${pct(k)}%</strong></div><div class="progress" style="margin-bottom:18px"><i style="width:${pct(k)}%"></i></div><div class="card">${co.items.map(x=>`<div class="lesson" data-id="${x[0]}"><div class="lesson-no">${x[0]}</div><div><div class="lesson-title">${x[1]}</div><div class="small muted">${x[2]}</div></div><span class="badge ${state.completed.includes(x[0])?'ok':''}">${state.completed.includes(x[0])?'完了':state.notes[x[0]]?'記録あり':'未実施'}</span></div>`).join('')}</div>`;c.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>go('lesson',e.dataset.id))}
function parseSiteData(text){
 const block=(text.match(/\[SITE_DATA\]([\s\S]*?)\[\/SITE_DATA\]/i)||[])[1]||text;
 const keys=['THEME','LEARNED','OUR_FACT','ISSUE','UNKNOWN','SOURCE'],out={};
 keys.forEach((k,i)=>{const next=keys.slice(i+1).join('|');const re=new RegExp('(?:^|\\n)'+k+'\\s*[:：]\\s*([\\s\\S]*?)(?=\\n(?:'+(next||'__END__')+')\\s*[:：]|$)','i');const m=block.match(re);out[k]=m?m[1].trim():''});
 return out;
}
function lesson(c,id){state.current=id;save();const it=item(id);if(!it)return go('home');const n=state.notes[id]||{};c.innerHTML=`<div class="hero"><span class="badge blue">${it.course}</span><h2>${id}｜${it.row[1]}</h2><p class="muted">今日のゴール：${it.row[2]}</p></div>
<div class="grid cols-2"><div class="card"><h3>① ChatGPTで30分学習</h3><p class="muted">今日専用のプロンプトをコピーしてChatGPTに貼り付けます。最後にサイト反映用データが出力されます。</p><button class="btn big-action" id="copyPrompt">ChatGPT学習プロンプトをコピー</button><details style="margin-top:12px"><summary>プロンプトを確認</summary><div class="prompt-box" id="promptText">${esc(promptFor(id))}</div></details></div>
<div class="card"><h3>② ChatGPTの結果をそのまま貼る</h3><p class="muted">学習終了時の [SITE_DATA] ～ [/SITE_DATA] を丸ごとコピーして貼り付けてください。</p><div class="field"><label>ChatGPTからコピーした内容</label><textarea id="bulkImport" class="import-box" placeholder="[SITE_DATA]\nTHEME: ...\nLEARNED: ...\nOUR_FACT: ...\nISSUE: ...\nUNKNOWN: ...\nSOURCE: ...\n[/SITE_DATA]"></textarea></div><button class="btn big-action" id="applyImport">貼り付け内容を反映</button></div></div>
<div class="card" style="margin-top:16px"><div class="section-head"><div><h3>③ 反映内容</h3><div class="muted">必要ならここで修正できます。保存すると「学習記録」と「会社の現在地」に同時反映します。</div></div></div><div class="form-grid"><div class="field full"><label>今日わかったこと｜KNOWLEDGE</label><textarea id="learned">${esc(n.learned||'')}</textarea></div><div class="field"><label>自社で確認できた事実｜OUR FACT</label><textarea id="fact">${esc(n.fact||'')}</textarea></div><div class="field"><label>会社の課題候補｜ISSUE</label><textarea id="issue">${esc(n.issue||'')}</textarea></div><div class="field"><label>まだ分からない／次に確認｜UNKNOWN</label><textarea id="next">${esc(n.next||'')}</textarea></div><div class="field full"><label>根拠・参考資料｜SOURCE</label><textarea id="source">${esc(n.source||'')}</textarea></div></div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:12px"><button class="btn" id="saveNote">保存</button><button class="btn secondary" id="toggleDone">${state.completed.includes(id)?'完了を取り消す':'保存して完了'}</button></div></div>`;
document.getElementById('copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText(promptFor(id));alert('学習プロンプトをコピーしました。ChatGPTに貼り付けて開始してください。')}catch(e){alert('コピーできませんでした。プロンプト表示から手動でコピーしてください。')}};
document.getElementById('applyImport').onclick=()=>{const d=parseSiteData(document.getElementById('bulkImport').value);if(!d.LEARNED&&!d.OUR_FACT&&!d.ISSUE&&!d.UNKNOWN){alert('サイト反映用データを読み取れませんでした。ChatGPTの [SITE_DATA] ブロックを丸ごと貼り付けてください。');return;}document.getElementById('learned').value=d.LEARNED||'';document.getElementById('fact').value=(d.OUR_FACT||'').replace(/^なし$/,'');document.getElementById('issue').value=(d.ISSUE||'').replace(/^なし$/,'');document.getElementById('next').value=(d.UNKNOWN||'').replace(/^なし$/,'');document.getElementById('source').value=(d.SOURCE||'').replace(/^なし$/,'');alert('反映しました。内容を確認して「保存」または「保存して完了」を押してください。')};
const collect=()=>{state.notes[id]={learned:document.getElementById('learned').value,fact:document.getElementById('fact').value,issue:document.getElementById('issue').value,next:document.getElementById('next').value,source:document.getElementById('source').value,date:new Date().toISOString().slice(0,10)};state.company=state.company||{};state.company[id]={fact:state.notes[id].fact,issue:state.notes[id].issue,unknown:state.notes[id].next,date:state.notes[id].date};save()};
document.getElementById('saveNote').onclick=()=>{collect();alert('学習記録と会社の現在地に保存しました')};document.getElementById('toggleDone').onclick=()=>{collect();state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();render('lesson',id)}}
function company(c){state.company=state.company||{};const rows=Object.entries(state.company).filter(([,x])=>x.fact||x.issue||x.unknown).sort((a,b)=>(b[1].date||'').localeCompare(a[1].date||''));const facts=rows.filter(([,x])=>x.fact).length,issues=rows.filter(([,x])=>x.issue).length,unknown=rows.filter(([,x])=>x.unknown).length;c.innerHTML=`<div class="hero"><span class="badge blue">OUR COMPANY</span><h2>会社の現在地</h2><p class="muted">毎日の学習から「確認できた事実・課題候補・未確認事項」だけを自動で集約します。ここで新たに入力する必要はありません。</p></div><div class="grid cols-3"><div class="card"><div class="small muted">事実があるテーマ</div><div class="metric">${facts}</div></div><div class="card"><div class="small muted">課題候補があるテーマ</div><div class="metric">${issues}</div></div><div class="card"><div class="small muted">未確認があるテーマ</div><div class="metric">${unknown}</div></div></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>分野・テーマ</th><th>OUR FACT｜確認済み</th><th>ISSUE｜課題候補</th><th>UNKNOWN｜未確認</th><th></th></tr></thead><tbody>${rows.map(([id,x])=>{const it=item(id);return `<tr><td><span class="badge">${id}</span><br><b>${it?esc(it.row[1]):id}</b></td><td>${nl(x.fact)}</td><td>${nl(x.issue)}</td><td>${nl(x.unknown)}</td><td><button class="btn light" onclick="go('lesson','${id}')">開く</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">まだ会社情報はありません。学習後のサイト反映用データを貼り付けると、ここへ自動で蓄積されます。</td></tr>'}</tbody></table></div>`}
function nl(v=''){return esc(v).replace(/\n/g,'<br>')}
function recent(limit=999){const rows=Object.entries(state.notes).filter(([,n])=>n.learned||n.fact||n.next).sort((a,b)=>(b[1].date||'').localeCompare(a[1].date||'')).slice(0,limit);return rows.length?rows.map(([id,n])=>{const it=item(id);return `<div class="list-row"><span class="badge ${state.completed.includes(id)?'ok':''}">${id}</span><div><b>${it?it.row[1]:id}</b><div class="small muted">${esc((n.learned||'').slice(0,80))}</div></div><button class="btn light" onclick="go('lesson','${id}')">開く</button></div>`}).join(''):'<div class="empty">まだ学習記録はありません。</div>'}
function records(c){c.innerHTML=`<div class="section-head"><div><h2>学習記録</h2><div class="muted">廃棄物・農業・余熱×農業の学習履歴を一元管理します。会社の状況は「会社の現在地」に自動集約されます。</div></div></div>${recent()}`}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`circular-learning-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{if(confirm('現在のデータをバックアップ内容で置き換えますか？')){state={...fresh(),...JSON.parse(r.result)};save();go('home')}}catch(e){alert('JSONを読み込めませんでした')}};r.readAsText(f)};renderNav();render('home');
